services:
    dbhost:
      image: quanticschoolofbusiness/103mysql
    app:
      build: app/.
      ports: 
        - 3006:3006
      depends_on:
        - dbhost
        - redis-server
    redis-server:
      image: redis
    email:
      build: email/.
      ports: 
        - 25:25
      depends_on:
        - redis-server
      environment:
        TO_ADDRESS: vv27@students.quantic.edu
        FROM_ADDRESS: viethaleob@gmail.com
        FROM_PASSWORD: qkvbkyumywvumvmb
    db-loader:
      build: db-loader/.
      volumes: 
        - /Users/havu/Documents/In Ireland/MSc Software Engineering/8. Microservices Architectures/2. Microservices II_Deploying and Testing/allergy-lab-watchfolder:/mnt/watchfolder/
      environment:
        FOLDER_PATH: /mnt/watchfolder/
        DB_NAME: allergy_info
        BD_USER: pythonapp
        DB_PASSWORD: secretPass123!
      depends_on:
        - dbhost